# Generated by Django 5.2.7 on 2025-10-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='theme_custom_color',
            field=models.CharField(blank=True, default='#6366F1', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='theme_glow_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('custom', 'Personalizado')], default='dark', max_length=10, null=True),
        ),
    ]
