# Generated by Django 5.2.7 on 2025-10-27 18:13

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empleado_theme_custom_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('activo_id', models.UUIDField(db_index=True)),
                ('probabilidad_fallo', models.FloatField()),
                ('dias_restantes_sugeridos', models.IntegerField(blank=True, null=True)),
                ('razon', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'prediccion_mantenimiento',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('departamento_id', models.UUIDField(db_index=True)),
                ('monto_sugerido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_cambio', models.FloatField()),
                ('razon', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'prediccion_presupuesto',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='theme_custom_color',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='theme_glow_enabled',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='activofijo',
            name='foto_activo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_activo),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_perfil),
        ),
        migrations.AlterField(
            model_name='log',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterModelTable(
            name='log',
            table='log_bitacora',
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='CORRECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion_problema', models.TextField()),
                ('notas_solucion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='api.activofijo')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to='api.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('ADVERTENCIA', 'Advertencia'), ('INFO', 'Info'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('url_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.empresa')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], default='basico', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('max_usuarios', models.PositiveIntegerField(default=5)),
                ('max_activos', models.PositiveIntegerField(default=50)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='api.empresa')),
            ],
        ),
    ]
