# Generated by Django 5.2.7 on 2025-10-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prediccionmantenimiento_prediccionpresupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='theme_custom_color',
            field=models.CharField(blank=True, default='#6366F1', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='theme_glow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='theme_preference',
            field=models.CharField(blank=True, default='dark', max_length=10, null=True),
        ),
    ]
