# Generated by Django 5.2.7 on 2025-10-29 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empleado_theme_custom_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['leido', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
