# Generated by Django 5.2.7 on 2025-10-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='api.departamento'),
        ),
    ]
