# Generated by Django 5.2.7 on 2025-11-16 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_depreciacionactivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('ENVIADA', 'Enviada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='GENERADA', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='api.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.proveedor')),
            ],
            options={
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='orden_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_creado', to='api.ordencompra'),
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('decision_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_decididas', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to='api.empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_compra', to='api.solicitudcompra'),
        ),
    ]
