# Generated by Django 5.2.7 on 2025-11-17 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ordencompra_activofijo_orden_compra_solicitudcompra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_presupuestarias', to='api.departamento')),
            ],
            options={
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPresupuestario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo')], default='GASTO', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_presupuestarios', to='api.ordencompra')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.partidapresupuestaria')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='partida_presupuestaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='api.partidapresupuestaria'),
        ),
        migrations.CreateModel(
            name='PeriodoPresupuestario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICACION', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente a partir de las partidas', max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_presupuestarios', to='api.empresa')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='api.periodopresupuestario'),
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.AlterUniqueTogether(
            name='partidapresupuestaria',
            unique_together={('periodo', 'departamento', 'nombre')},
        ),
    ]
