# Generated by Django 5.2.8 on 2025-11-18 20:31

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_budget_module_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to=api.models.upload_path_mantenimiento)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.mantenimiento')),
            ],
        ),
    ]
