# Generated by Django 5.2.8 on 2025-11-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_mantenimiento_fotos_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientofoto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_subidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimientofoto',
            name='tipo',
            field=models.CharField(choices=[('PROBLEMA', 'Problema'), ('SOLUCION', 'Solución')], default='PROBLEMA', max_length=20),
        ),
    ]
