# Generated by Django 5.2.8 on 2025-11-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mantenimientofoto_subido_por_mantenimientofoto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciacionactivo',
            name='depreciation_type',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Línea Recta'), ('DECLINING_BALANCE', 'Saldo Decreciente'), ('UNITS_OF_PRODUCTION', 'Unidades de Producción'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
    ]
