# Generated by Django 5.2.8 on 2025-11-19 03:36

from django.db import migrations


def add_view_presupuesto_report_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.create(
        nombre='view_presupuesto_report',
        descripcion='Permite ver los reportes del módulo de presupuestos.'
    )

def remove_view_presupuesto_report_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.filter(nombre='view_presupuesto_report').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_depreciacionactivo_depreciation_type'),
    ]

    operations = [
        migrations.RunPython(add_view_presupuesto_report_permission, remove_view_presupuesto_report_permission),
    ]
