# Generated by Django 5.2.8 on 2025-11-19 04:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_view_presupuesto_report_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposicionActivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_disposicion', models.CharField(choices=[('VENTA', 'Venta'), ('BAJA', 'Baja por Obsolescencia/Daño'), ('DONACION', 'Donación'), ('ROBO', 'Robo/Pérdida'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_disposicion', models.DateField(default=django.utils.timezone.now)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('razon', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones', to='api.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposiciones_activos', to='api.empresa')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disposición de Activo',
                'verbose_name_plural': 'Disposiciones de Activos',
                'ordering': ['-fecha_disposicion'],
            },
        ),
    ]
