# Generated by Django 5.2.8 on 2025-11-19 04:32

from django.db import migrations

def add_manage_disposicion_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.create(
        nombre='manage_disposicion',
        descripcion='Permite gestionar las disposiciones de activos (crear, editar, eliminar).'
    )

def remove_manage_disposicion_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.filter(nombre='manage_disposicion').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_disposicionactivo'),
    ]

    operations = [
        migrations.RunPython(add_manage_disposicion_permission, reverse_code=remove_manage_disposicion_permission),
    ]