# Generated by Django 5.2.8 on 2025-11-19 05:53

from django.db import migrations

def add_view_disposicion_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.create(
        nombre='view_disposicion',
        descripcion='Permite ver las disposiciones de activos.'
    )

def remove_view_disposicion_permission(apps, schema_editor):
    Permisos = apps.get_model('api', 'Permisos')
    Permisos.objects.filter(nombre='view_disposicion').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_manage_disposicion_permission'),
    ]

    operations = [
        migrations.RunPython(add_view_disposicion_permission, reverse_code=remove_view_disposicion_permission),
    ]