# Generated by Django 5.2.8 on 2025-11-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_view_disposicion_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Token'),
        ),
    ]
