// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr5t8-7ZG88zESwWmWCv81ulokASPwN8o',
    appId: '1:1083949969226:web:54e9154a28bdcc5d8edbb3',
    messagingSenderId: '1083949969226',
    projectId: 'actfijopresupuesto',
    authDomain: 'actfijopresupuesto.firebaseapp.com',
    storageBucket: 'actfijopresupuesto.firebasestorage.app',
    measurementId: 'G-00CST02ZM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54nqUs1ABUR3tyf5dNuCNw_duHDEtLTY',
    appId: '1:1083949969226:android:ac5987ca7d8b76b08edbb3',
    messagingSenderId: '1083949969226',
    projectId: 'actfijopresupuesto',
    storageBucket: 'actfijopresupuesto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLM2wxWVt99Wo7VlnDopDmTerojjco-5w',
    appId: '1:1083949969226:ios:96dc508c9b1545358edbb3',
    messagingSenderId: '1083949969226',
    projectId: 'actfijopresupuesto',
    storageBucket: 'actfijopresupuesto.firebasestorage.app',
    iosBundleId: 'com.example.movil2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLM2wxWVt99Wo7VlnDopDmTerojjco-5w',
    appId: '1:1083949969226:ios:58fdd155775b3de38edbb3',
    messagingSenderId: '1083949969226',
    projectId: 'actfijopresupuesto',
    storageBucket: 'actfijopresupuesto.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr5t8-7ZG88zESwWmWCv81ulokASPwN8o',
    appId: '1:1083949969226:web:eae59178aaa6f61b8edbb3',
    messagingSenderId: '1083949969226',
    projectId: 'actfijopresupuesto',
    authDomain: 'actfijopresupuesto.firebaseapp.com',
    storageBucket: 'actfijopresupuesto.firebasestorage.app',
    measurementId: 'G-9MHLB9DY6S',
  );
}
